services:
    stg.cas_service:
        class: Stg\Bundle\CasBundle\Service\CasService
        arguments:
           - '%cas_config%'
           - '@logger'
           - '@router'
    stg.cas_authenticator:
        class: Stg\Bundle\CasBundle\Security\CasAuthenticator
        arguments:
            - '@stg.cas_service'
            - '@security.helper'
    stg.cas_logout:
        class: Stg\Bundle\CasBundle\Security\EventListener\SessionLogoutListener
        arguments:
            - '@stg.cas_service'

